//! JVM bytecode opcodes and instruction decoding.

/// JVM opcodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Opcode {
    Nop = 0x00,
    AconstNull = 0x01,
    IconstM1 = 0x02,
    Iconst0 = 0x03,
    Iconst1 = 0x04,
    Iconst2 = 0x05,
    Iconst3 = 0x06,
    Iconst4 = 0x07,
    Iconst5 = 0x08,
    Lconst0 = 0x09,
    Lconst1 = 0x0A,
    Fconst0 = 0x0B,
    Fconst1 = 0x0C,
    Fconst2 = 0x0D,
    Dconst0 = 0x0E,
    Dconst1 = 0x0F,
    Bipush = 0x10,
    Sipush = 0x11,
    Ldc = 0x12,
    LdcW = 0x13,
    Ldc2W = 0x14,
    Iload = 0x15,
    Lload = 0x16,
    Fload = 0x17,
    Dload = 0x18,
    Aload = 0x19,
    Iload0 = 0x1A,
    Iload1 = 0x1B,
    Iload2 = 0x1C,
    Iload3 = 0x1D,
    Lload0 = 0x1E,
    Lload1 = 0x1F,
    Lload2 = 0x20,
    Lload3 = 0x21,
    Fload0 = 0x22,
    Fload1 = 0x23,
    Fload2 = 0x24,
    Fload3 = 0x25,
    Dload0 = 0x26,
    Dload1 = 0x27,
    Dload2 = 0x28,
    Dload3 = 0x29,
    Aload0 = 0x2A,
    Aload1 = 0x2B,
    Aload2 = 0x2C,
    Aload3 = 0x2D,
    Iaload = 0x2E,
    Laload = 0x2F,
    Faload = 0x30,
    Daload = 0x31,
    Aaload = 0x32,
    Baload = 0x33,
    Caload = 0x34,
    Saload = 0x35,
    Istore = 0x36,
    Lstore = 0x37,
    Fstore = 0x38,
    Dstore = 0x39,
    Astore = 0x3A,
    Istore0 = 0x3B,
    Istore1 = 0x3C,
    Istore2 = 0x3D,
    Istore3 = 0x3E,
    Lstore0 = 0x3F,
    Lstore1 = 0x40,
    Lstore2 = 0x41,
    Lstore3 = 0x42,
    Fstore0 = 0x43,
    Fstore1 = 0x44,
    Fstore2 = 0x45,
    Fstore3 = 0x46,
    Dstore0 = 0x47,
    Dstore1 = 0x48,
    Dstore2 = 0x49,
    Dstore3 = 0x4A,
    Astore0 = 0x4B,
    Astore1 = 0x4C,
    Astore2 = 0x4D,
    Astore3 = 0x4E,
    Iastore = 0x4F,
    Lastore = 0x50,
    Fastore = 0x51,
    Dastore = 0x52,
    Aastore = 0x53,
    Bastore = 0x54,
    Castore = 0x55,
    Sastore = 0x56,
    Pop = 0x57,
    Pop2 = 0x58,
    Dup = 0x59,
    DupX1 = 0x5A,
    DupX2 = 0x5B,
    Dup2 = 0x5C,
    Dup2X1 = 0x5D,
    Dup2X2 = 0x5E,
    Swap = 0x5F,
    Iadd = 0x60,
    Ladd = 0x61,
    Fadd = 0x62,
    Dadd = 0x63,
    Isub = 0x64,
    Lsub = 0x65,
    Fsub = 0x66,
    Dsub = 0x67,
    Imul = 0x68,
    Lmul = 0x69,
    Fmul = 0x6A,
    Dmul = 0x6B,
    Idiv = 0x6C,
    Ldiv = 0x6D,
    Fdiv = 0x6E,
    Ddiv = 0x6F,
    Irem = 0x70,
    Lrem = 0x71,
    Frem = 0x72,
    Drem = 0x73,
    Ineg = 0x74,
    Lneg = 0x75,
    Fneg = 0x76,
    Dneg = 0x77,
    Ishl = 0x78,
    Lshl = 0x79,
    Ishr = 0x7A,
    Lshr = 0x7B,
    Iushr = 0x7C,
    Lushr = 0x7D,
    Iand = 0x7E,
    Land = 0x7F,
    Ior = 0x80,
    Lor = 0x81,
    Ixor = 0x82,
    Lxor = 0x83,
    Iinc = 0x84,
    I2l = 0x85,
    I2f = 0x86,
    I2d = 0x87,
    L2i = 0x88,
    L2f = 0x89,
    L2d = 0x8A,
    F2i = 0x8B,
    F2l = 0x8C,
    F2d = 0x8D,
    D2i = 0x8E,
    D2l = 0x8F,
    D2f = 0x90,
    I2b = 0x91,
    I2c = 0x92,
    I2s = 0x93,
    Lcmp = 0x94,
    Fcmpl = 0x95,
    Fcmpg = 0x96,
    Dcmpl = 0x97,
    Dcmpg = 0x98,
    Ifeq = 0x99,
    Ifne = 0x9A,
    Iflt = 0x9B,
    Ifge = 0x9C,
    Ifgt = 0x9D,
    Ifle = 0x9E,
    IfIcmpeq = 0x9F,
    IfIcmpne = 0xA0,
    IfIcmplt = 0xA1,
    IfIcmpge = 0xA2,
    IfIcmpgt = 0xA3,
    IfIcmple = 0xA4,
    IfAcmpeq = 0xA5,
    IfAcmpne = 0xA6,
    Goto = 0xA7,
    Jsr = 0xA8,
    Ret = 0xA9,
    Tableswitch = 0xAA,
    Lookupswitch = 0xAB,
    Ireturn = 0xAC,
    Lreturn = 0xAD,
    Freturn = 0xAE,
    Dreturn = 0xAF,
    Areturn = 0xB0,
    Return = 0xB1,
    Getstatic = 0xB2,
    Putstatic = 0xB3,
    Getfield = 0xB4,
    Putfield = 0xB5,
    Invokevirtual = 0xB6,
    Invokespecial = 0xB7,
    Invokestatic = 0xB8,
    Invokeinterface = 0xB9,
    Invokedynamic = 0xBA,
    New = 0xBB,
    Newarray = 0xBC,
    Anewarray = 0xBD,
    Arraylength = 0xBE,
    Athrow = 0xBF,
    Checkcast = 0xC0,
    Instanceof = 0xC1,
    Monitorenter = 0xC2,
    Monitorexit = 0xC3,
    Wide = 0xC4,
    Multianewarray = 0xC5,
    Ifnull = 0xC6,
    Ifnonnull = 0xC7,
    GotoW = 0xC8,
    JsrW = 0xC9,
}

impl Opcode {
    /// Decode an opcode from a byte.
    pub fn from_byte(byte: u8) -> Option<Self> {
        if byte <= 0xC9 {
            // Safety: all values 0x00..=0xC9 have defined variants (with gaps handled)
            Some(unsafe { core::mem::transmute(byte) })
        } else {
            None
        }
    }

    /// Size of instruction operands (not including the opcode byte itself).
    /// Returns None for variable-length instructions.
    pub fn operand_size(self) -> Option<usize> {
        match self {
            Self::Nop | Self::AconstNull => Some(0),
            Self::IconstM1 | Self::Iconst0 | Self::Iconst1 | Self::Iconst2
            | Self::Iconst3 | Self::Iconst4 | Self::Iconst5 => Some(0),
            Self::Lconst0 | Self::Lconst1 => Some(0),
            Self::Fconst0 | Self::Fconst1 | Self::Fconst2 => Some(0),
            Self::Dconst0 | Self::Dconst1 => Some(0),
            Self::Bipush => Some(1),
            Self::Sipush => Some(2),
            Self::Ldc => Some(1),
            Self::LdcW | Self::Ldc2W => Some(2),
            Self::Iload | Self::Lload | Self::Fload | Self::Dload | Self::Aload => Some(1),
            Self::Iload0 | Self::Iload1 | Self::Iload2 | Self::Iload3 => Some(0),
            Self::Lload0 | Self::Lload1 | Self::Lload2 | Self::Lload3 => Some(0),
            Self::Fload0 | Self::Fload1 | Self::Fload2 | Self::Fload3 => Some(0),
            Self::Dload0 | Self::Dload1 | Self::Dload2 | Self::Dload3 => Some(0),
            Self::Aload0 | Self::Aload1 | Self::Aload2 | Self::Aload3 => Some(0),
            Self::Iaload | Self::Laload | Self::Faload | Self::Daload
            | Self::Aaload | Self::Baload | Self::Caload | Self::Saload => Some(0),
            Self::Istore | Self::Lstore | Self::Fstore | Self::Dstore | Self::Astore => Some(1),
            Self::Istore0 | Self::Istore1 | Self::Istore2 | Self::Istore3 => Some(0),
            Self::Lstore0 | Self::Lstore1 | Self::Lstore2 | Self::Lstore3 => Some(0),
            Self::Fstore0 | Self::Fstore1 | Self::Fstore2 | Self::Fstore3 => Some(0),
            Self::Dstore0 | Self::Dstore1 | Self::Dstore2 | Self::Dstore3 => Some(0),
            Self::Astore0 | Self::Astore1 | Self::Astore2 | Self::Astore3 => Some(0),
            Self::Pop | Self::Pop2 | Self::Dup | Self::DupX1 | Self::DupX2
            | Self::Dup2 | Self::Dup2X1 | Self::Dup2X2 | Self::Swap => Some(0),
            Self::Iadd | Self::Ladd | Self::Fadd | Self::Dadd => Some(0),
            Self::Isub | Self::Lsub | Self::Fsub | Self::Dsub => Some(0),
            Self::Imul | Self::Lmul | Self::Fmul | Self::Dmul => Some(0),
            Self::Idiv | Self::Ldiv | Self::Fdiv | Self::Ddiv => Some(0),
            Self::Irem | Self::Lrem | Self::Frem | Self::Drem => Some(0),
            Self::Ineg | Self::Lneg | Self::Fneg | Self::Dneg => Some(0),
            Self::Ishl | Self::Lshl | Self::Ishr | Self::Lshr
            | Self::Iushr | Self::Lushr => Some(0),
            Self::Iand | Self::Land | Self::Ior | Self::Lor
            | Self::Ixor | Self::Lxor => Some(0),
            Self::Iinc => Some(2),
            Self::I2l | Self::I2f | Self::I2d | Self::L2i | Self::L2f | Self::L2d
            | Self::F2i | Self::F2l | Self::F2d | Self::D2i | Self::D2l | Self::D2f
            | Self::I2b | Self::I2c | Self::I2s => Some(0),
            Self::Lcmp | Self::Fcmpl | Self::Fcmpg | Self::Dcmpl | Self::Dcmpg => Some(0),
            Self::Ifeq | Self::Ifne | Self::Iflt | Self::Ifge | Self::Ifgt | Self::Ifle => Some(2),
            Self::IfIcmpeq | Self::IfIcmpne | Self::IfIcmplt | Self::IfIcmpge
            | Self::IfIcmpgt | Self::IfIcmple => Some(2),
            Self::IfAcmpeq | Self::IfAcmpne => Some(2),
            Self::Goto => Some(2),
            Self::Jsr => Some(2),
            Self::Ret => Some(1),
            Self::Ireturn | Self::Lreturn | Self::Freturn | Self::Dreturn
            | Self::Areturn | Self::Return => Some(0),
            Self::Getstatic | Self::Putstatic | Self::Getfield | Self::Putfield => Some(2),
            Self::Invokevirtual | Self::Invokespecial | Self::Invokestatic => Some(2),
            Self::Invokeinterface => Some(4),
            Self::Invokedynamic => Some(4),
            Self::New => Some(2),
            Self::Newarray => Some(1),
            Self::Anewarray => Some(2),
            Self::Arraylength => Some(0),
            Self::Athrow => Some(0),
            Self::Checkcast | Self::Instanceof => Some(2),
            Self::Monitorenter | Self::Monitorexit => Some(0),
            Self::Multianewarray => Some(3),
            Self::Ifnull | Self::Ifnonnull => Some(2),
            Self::GotoW | Self::JsrW => Some(4),
            Self::Tableswitch | Self::Lookupswitch | Self::Wide => None,
            _ => Some(0),
        }
    }
}
